const newSurveyCSVARRAY = 
    [
        {
            "type": "open",
            "questions": "What is your first name?",
            "dataCapture": "NAME",
            "autoFill": "name",
            "category": "General",
            "rows": "",
            "answers": "[]"
        },
        {
            "type": "single",
            "questions": "What is your current student designation?",
            "dataCapture": "DESIGNATION",
            "autoFill": "designation",
            "category": "General",
            "rows": "",
            "answers": "[Freshman, Sophomore, Junior, Senior, Graduate Level, Other]"
        },
        {
            "type": "single",
            "questions": "Is your major STEM? (Science, Technology, Engineering and Mathematics)",
            "dataCapture": "",
            "autoFill": "",
            "category": "General",
            "rows": "",
            "answers": "[Yes, No, if Yes, what's your GPA]"
        },
        {
            "type": "open",
            "questions": "What's your current GPA?",
            "dataCapture": "",
            "autoFill": "",
            "category": "General",
            "rows": "",
            "answers": "[above 3.5, 3-3.5, below 3]"
        },
        {
            "type": "open",
            "questions": "###NAME, what is your email?",
            "dataCapture": "EMAIL",
            "autoFill": "email",
            "category": "General",
            "rows": "",
            "answers": "[]"
        },
        {
            "type": "single",
            "questions": "Which best describes your level of interest in Machine Learning?",
            "dataCapture": "",
            "autoFill": "",
            "category": "General",
            "rows": "",
            "answers": "['Long term career goal', 'Personal interest', 'Hobby', 'I don't know']"
        },
        {
            "type": "single",
            "questions": "Can you descrive your level of exposure to Machine Learning",
            "dataCapture": "",
            "autoFill": "",
            "category": "General",
            "rows": "",
            "answers": "['Exploratory', 'Observer', 'Enthusiast', 'Passionate', ' I don't know]"
        },
        {
            "type": "open",
            "questions": "Let's discuss your achiemvements in ML so far?  ",
            "dataCapture": "",
            "autoFill": "",
            "category": "General",
            "rows": "",
            "answers": "[]"
        },
        {
            "type": "single",
            "questions": "How many online ML certifications have you been awarded?  ",
            "dataCapture": "",
            "autoFill": "",
            "category": "General",
            "rows": "",
            "answers": "[None, 1-3, 4-6, 7-9, above 9]"
        },
        {
            "type": "single",
            "questions": "Have you been a part of any ML Internships at organizations?",
            "dataCapture": "",
            "autoFill": "",
            "category": "General",
            "rows": "",
            "answers": "['Yes', 'No']"
        },
        {
            "type": "multiple",
            "questions": "Do you plan to enter the workforce as a Data Scientist, ML engineer, or Data Analyst in the future?  ",
            "dataCapture": "",
            "autoFill": "",
            "category": "General",
            "rows": "",
            "answers": "[Data Scientist, ML Engineer, Data Analyst, other] "
        },
        {
            "type": "multiple",
            "questions": "What data types do you prefer to work with on your current projects?",
            "dataCapture": "",
            "autoFill": "",
            "category": "Data Preparation",
            "rows": "",
            "answers": "['Text', 'Numerical', 'Geospatial', 'Images', 'Audio', 'Video', 'Other', 'I do not know']"
        },
        {
            "type": "single",
            "questions": "What is the largest dataset that you have interacted with in terms of rows?",
            "dataCapture": "",
            "autoFill": "",
            "category": "Data Preparation",
            "rows": "",
            "answers": "[ Under 5K, 5K-50K, 50K-500K, 1M+, I don't know]"
        },
        {
            "type": "multiple",
            "questions": "Which IDEs have you worked with to prepare data?  ",
            "dataCapture": "",
            "autoFill": "",
            "category": "Data Preparation",
            "rows": "",
            "answers": "[Jupyter Notebook, SageMaker, Google Colab, GitHub, Other]"
        },
        {
            "type": "single",
            "questions": "Which of the following best describes your aptitude for accessing data?",
            "dataCapture": "",
            "autoFill": "",
            "category": "Data Preparation",
            "rows": "",
            "answers": "['There is a standardized protocol for accessing data across the organization', 'Each department/division constructs its own protocol for accessing data', 'Individuals set up their own protocols for accessing data', 'I do not know']"
        },
        {
            "type": "multiple",
            "questions": "I can, ",
            "dataCapture": "",
            "autoFill": "",
            "category": "Data Preparation",
            "rows": "",
            "answers": "['Integrate internal data between different systems/departments', 'Host/maintain a live data feed', 'Backup and retrieve historical data', 'Ingest data from external sources', 'Query live data', 'None of the above', 'I do not know']"
        },
        {
            "type": "single",
            "questions": "Have you been part of identifying the problem statement and establish a baseline?",
            "dataCapture": "",
            "autoFill": "",
            "category": "Data Preparation",
            "rows": "",
            "answers": "['Yes' , 'No']"
        },
        {
            "type": "multiple",
            "questions": "List out the Python libraries/architecture you have had exposure to, for Data Analysis, maching learning and deep learning?",
            "dataCapture": "",
            "autoFill": "",
            "category": "Modeling",
            "rows": "Choose Many",
            "answers": "[SciPy, Pandas, Numpy, Scikit learn, Tensorflow, Pytorch, Transformer, OpenCV, other, none of the above] "
        },
        {
            "type": "single",
            "questions": "In your coursework, have you developed any models for research through your academic institution or lab work?  If so, how many?  ",
            "dataCapture": "",
            "autoFill": "",
            "category": "Modeling",
            "rows": "",
            "answers": "['0', '1-5', '6-10', '11-15', '16-20', '21+']"
        },
        {
            "type": "multiple",
            "questions": "Regarding Maching Learning Engineering, have you been exposed to any of these?",
            "dataCapture": "",
            "autoFill": "",
            "category": "Modeling",
            "rows": "",
            "answers": "[Flask, Flink, Snowflake, AWS SageMaker, Kubernetes, Spark, Docker] "
        },
        {
            "type": "single",
            "questions": "What data visualization tools have you been exposed to?  ",
            "dataCapture": "",
            "autoFill": "",
            "category": "Modeling",
            "rows": "",
            "answers": "[Tableau, Plotly, Matplotlib, Seaborn, Other]"
        },
        {
            "type": "multiple",
            "questions": "What kinds of metrics that your machine learning models have used in development?",
            "dataCapture": "",
            "autoFill": "",
            "category": "Modeling",
            "rows": "",
            "answers": "['RMSE', 'R2', 'Accuracy', 'F1', 'Precision', 'Recall', 'ROC_AUC score', 'NDCG', 'Other', 'I do not know']"
        },
        {
            "type": "multiple",
            "questions": "What MLOps coursework would you like to focus on?  ",
            "dataCapture": "",
            "autoFill": "",
            "category": "Modeling",
            "rows": "",
            "answers": "[ API Integration and Documentation, Model Function Testing, Establishing Secure Data Pipelines, Identifying KPIs, Real time inference, Latency Reduction]"
        },
        {
            "type": "single",
            "questions": "On average, how long does it take for you potentially deploy a model?",
            "dataCapture": "",
            "autoFill": "",
            "category": "Modeling",
            "rows": "",
            "answers": "['Less than 1 week', '1-3 weeks', '4-8 weeks', 'More than 8 weeks', 'I do not know']"
        },
        {
            "type": "single",
            "questions": "Which particular ML lifecycle appeals to you most?  ",
            "dataCapture": "",
            "autoFill": "",
            "category": "Modeling",
            "rows": "",
            "answers": "[ Data Preparation, Model Development and Testing, Model Deployment, Model Monitoring, or Assessing Business Value using ML]"
        },
        {
            "type": "single",
            "questions": "Does your current academic institution offer specific model monitoring coursework?",
            "dataCapture": "",
            "autoFill": "",
            "category": "Modeling",
            "rows": "Expand?",
            "answers": "[ Yes, Not currently]"
        },
        {
            "type": "multiple",
            "questions": "What types of ML Applications are you most interested in?  ",
            "dataCapture": "",
            "autoFill": "",
            "category": "Career Trajectory",
            "rows": "",
            "answers": "[Predictive Analysis, Anamoly Detection, NLP, Computer Vision, Deep Learning, Robotics, Other]"
        },
        {
            "type": "single",
            "questions": "In your opinion, which area of the ML Lifecycle offers the greatest value for ML?  ",
            "dataCapture": "",
            "autoFill": "",
            "category": "Career Trajectory",
            "rows": "",
            "answers": "[Data Preparation, Model Development, Model Deployment, Model Monitoring, or Business Value, I don't know]"
        },
        {
            "type": "multiple",
            "questions": "Do you have ML related career goal? If yes then what is it?",
            "dataCapture": "",
            "autoFill": "",
            "category": "Career Trajectory",
            "rows": "",
            "answers": "[Machine learning engineer, MLOps and Deployment, Computer vision / NLP / computational linguistics specialists, Data Scientist, I don't know]"
        },
        {
            "type": "multiple",
            "questions": "What have you learned/are you planning to learn for a career in machine learning?",
            "dataCapture": "",
            "autoFill": "",
            "category": "Career Trajectory",
            "rows": "",
            "answers": "['Programming in Python/C++/Java and corresponding ML libraries/frameworks', 'Statistical Analysis with R', 'Data wrangling with Pandas and Numpy', 'Deep learning, neural network principles and engineering frameworks with Tensorflow and PyTorch', 'Deployment tools like AWS SageMaker', 'I don't know']"
        },
        {
            "type": "multiple",
            "questions": "Has your academic institution considered doing these following things for your career development?",
            "dataCapture": "",
            "autoFill": "",
            "category": "Career Trajectory",
            "rows": "",
            "answers": "['Resume building', 'Practice your learning by working on real world projects', 'Compete on some platforms like Kaggle', 'Interview preparation', 'None of Above']"
        },
        {
            "type": "multiple",
            "questions": "What leadership styles that you most identified with?",
            "dataCapture": "",
            "autoFill": "",
            "category": "Career Trajectory",
            "rows": "",
            "answers": "[Transactional', 'Democratic,' Transformational, 'Servant,' 'Charasmatic,']"
        },
        {
            "type": "single",
            "questions": "How do we perform Bayesian classification when some features are missing?",
            "dataCapture": "",
            "autoFill": "",
            "category": "ML Aptitude",
            "rows": "",
            "answers": "['We assuming the missing values as the mean of all values.', 'We ignore the missing features.', 'We integrate the posteriors probabilities over the missing features.', 'Drop the features completely if most of the entries are missing.']"
        },
        {
            "type": "single",
            "questions": "The robotic arm will be able to paint every corner in the automotive parts while minimizing the quantity of paint wasted in the process. Which learning technique is used in this problem?",
            "dataCapture": "",
            "autoFill": "",
            "category": "ML Aptitude",
            "rows": "",
            "answers": "['Supervised Learning', 'Unsupervised Learning', 'Both Supervised and Unsupervised Learning', 'Reinforcement Learning']"
        },
        {
            "type": "multiple",
            "questions": "What kind of distance metric(s) are suitable for categorical variables to find the closest neighbors?",
            "dataCapture": "",
            "autoFill": "",
            "category": "ML Aptitude",
            "rows": "",
            "answers": "['Euclidean distance', 'Manhattan distance', 'Minkowski distance', 'Hamming Distance']"
        },
        {
            "type": "single",
            "questions": "Which of the following is FALSE about Correlation and Covariance?",
            "dataCapture": "",
            "autoFill": "",
            "category": "ML Aptitude",
            "rows": "",
            "answers": "['A zero correlation does not necessarily imply independence between variables', 'Correlation and covariance values are the same', 'The covariance and correlation are always the same sign', 'Correlation is the standardized version of Covariance']"
        },
        {
            "type": "single",
            "questions": "Which of the following is FALSE about Deep Learning and Machine Learning algorithms?",
            "dataCapture": "",
            "autoFill": "",
            "category": "ML Aptitude",
            "rows": "",
            "answers": "['Deep Learning algorithms work efficiently on a high amount of data','Feature Extraction needs to be done manually in both ML and DL algorithms', ' Deep Learning algorithms are best suited for unstructured data', 'Deep Learning algorithms require high computational power']"
        },
        {
            "type": "single",
            "questions": "Do you think your Academic Institution puts enogh emphasis on the business value of Machine Learning?",
            "dataCapture": "",
            "autoFill": "",
            "category": "Business Value",
            "rows": "",
            "answers": "['Yes', 'No', 'I do not know']"
        },
        {
            "type": "single",
            "questions": "If there was a course on business value using ML, would that prompt a different career trajactory?  ",
            "dataCapture": "",
            "autoFill": "",
            "category": "Business Value",
            "rows": "",
            "answers": "[Yes, No, I do not know']"
        },
        {
            "type": "single",
            "questions": "How important is machine learning for your overall career path?",
            "dataCapture": "",
            "autoFill": "",
            "category": "Business Value",
            "rows": "",
            "answers": "['Not important at all', 'Slightly important', 'Somewhat important', 'Important', 'Very important']"
        },
        {
            "type": "multiple",
            "questions": "Please identify any experience you've had aligning business objectives with machine learning models.",
            "dataCapture": "",
            "autoFill": "",
            "category": "Business Value",
            "rows": "",
            "answers": "['The data we need is not available', 'We have no models to align our objectives with', 'We do not have the staff to align machine learning models with business objectives', 'We do not have the resources to align machine learning models with business objectives', 'Other']"
        },
        {
            "type": "multiple",
            "questions": "What has been the most challenging aspect(s) of using machine learning models?",
            "dataCapture": "",
            "autoFill": "",
            "category": "General",
            "rows": "",
            "answers": "['Not enough data', 'Low data quality', 'Data centralization', 'Lack of technical talent', 'Limited budget', 'Deployment of models or results', 'Developing a strategy for use', 'Labeling data', 'I do not know']"
        },
        {
            "type": "multiple",
            "questions": "What has been the most rewarding aspect(s) of using machine learning models?",
            "dataCapture": "",
            "autoFill": "",
            "category": "General",
            "rows": "",
            "answers": "['Enhanced efficiency', 'Improved operations', 'Improved decision-making abilities', 'New streams of revenue', 'Improved revenue streams', 'I do not know']"
        },
        {
            "type": "multiple",
            "questions": "How did you solve the challenge(s) you identified?",
            "dataCapture": "",
            "autoFill": "",
            "category": "General",
            "rows": "",
            "answers": "['Developed an internal solution', 'Outsourced the solution', 'It has not been solved yet']"
        },
        {
            "type": "single",
            "questions": "###NAME, would you be willing to take our survey again in 4 months?",
            "dataCapture": "",
            "autoFill": "",
            "category": "",
            "rows": "",
            "answers": "['Yes', 'No']"
        },
        {
            "type": "open",
            "questions": "What is the best email for the person who would be most knowledgable about machine learning at your company?",
            "dataCapture": "",
            "autoFill": "",
            "category": "",
            "rows": "",
            "answers": "[]"
        }
    ]

const frozenCSVARRAY = [
    {
        "questionId": "sy9SkVGXW9f1",
        "type": "open",
        "questions": "What is your first name?",
        "dataCapture": "NAME",
        "autoFill": "name",
        "category": "General",
        "rows": "",
        "answers": "[]",
        "answerId": "[\"7a8LfLIMdEy6\"]",
        "scores": ""
    },
    {
        "questionId": "ktGqfhk10tZQ",
        "type": "single",
        "questions": "What is your current student designation?",
        "dataCapture": "DESIGNATION",
        "autoFill": "designation",
        "category": "General",
        "rows": "",
        "answers": "[Freshman, Sophomore, Junior, Senior, Graduate Level,  'Other']",
        "answerId": "[\"Cy56yNoP1SeI\",\"ZHpeNF2qSKuT\",\"uegJeAKkgN6X\",\"LXcdWaf6eRom\",\"LaBilnZqtBlP\",\"IrH7EFky6Wlg\"]",
        "scores": ""
    },
    {
        "questionId": "3RkTh825aRsT",
        "type": "single",
        "questions": "Is your major STEM? (Science, Technology, Engineering and Mathematics)",
        "dataCapture": "",
        "autoFill": "",
        "category": "General",
        "rows": "",
        "answers": "[Yes, No, if Yes, what's your GPA]",
        "answerId": "[\"ARkOogKhls8m\",\"lxlI88NrGIFq\",\"c5ePwI9PjrsC\",\"xPZgHLubrEZ1\"]",
        "scores": ""
    },
    {
        "questionId": "U25qKAuGMkZm",
        "type": "open",
        "questions": "What's your current GPA?",
        "dataCapture": "",
        "autoFill": "",
        "category": "General",
        "rows": "",
        "answers": "[above 3.5, 3-3.5, below 3]",
        "answerId": "[\"CcnuIc0qhMKF\",\"WG7jCVGksL7b\",\"4NkkGXhXXhB5\"]",
        "scores": ""
    },
    {
        "questionId": "BNOQH2CfYkar",
        "type": "open",
        "questions": "###NAME, what is your email?",
        "dataCapture": "EMAIL",
        "autoFill": "email",
        "category": "General",
        "rows": "",
        "answers": "[]",
        "answerId": "[\"x7biuF0npcY3\"]",
        "scores": ""
    },
    {
        "questionId": "Kb6TTYeDpTpH",
        "type": "single",
        "questions": "Which best describes your level of interest in Machine Learning?",
        "dataCapture": "",
        "autoFill": "",
        "category": "General",
        "rows": "",
        "answers": "['Long term career goal', 'Personal interest', 'Hobby', 'I don't know']",
        "answerId": "[\"kadbCNHKSSjg\",\"EW1vZthJsoDc\",\"COEWW87I19ee\",\"f7igtkZXJAyj\"]",
        "scores": "[3,2,1,0]"
    },
    {
        "questionId": "vQkpEkv9nvE1",
        "type": "single",
        "questions": "Can you descrive your level of exposure to Machine Learning",
        "dataCapture": "",
        "autoFill": "",
        "category": "General",
        "rows": "",
        "answers": "['Exploratory', 'Observer', 'Enthusiast', 'Passionate', ' I don't know]",
        "answerId": "[\"gBpsH0kc0I1i\",\"1dXm2r7THrI2\",\"ryQuEeR7ArT7\",\"kWOQa3P6G1Te\",\"6gurjoqd3PSx\"]",
        "scores": "[1,2,3,4,0]"
    },
    {
        "questionId": "rduebL4mUuUL",
        "type": "open",
        "questions": "Let's discuss your achiemvements in ML so far?  ",
        "dataCapture": "",
        "autoFill": "",
        "category": "General",
        "rows": "",
        "answers": "[]",
        "answerId": "[\"utMHxAAUvsp8\"]",
        "scores": ""
    },
    {
        "questionId": "QrH3MPbcM4jJ",
        "type": "single",
        "questions": "How many online ML certifications have you been awarded?  ",
        "dataCapture": "",
        "autoFill": "",
        "category": "General",
        "rows": "",
        "answers": "[None, 1-3, 4-6, 7-9, above 9]",
        "answerId": "[\"NkJ8UgdPqcEX\",\"K2E9gcCa5oxE\",\"5FsCPeqIGCZf\",\"ak9LpRqfso5w\",\"4WG1Sfct4xEy\"]",
        "scores": "[0,1,2,3,4]"
    },
    {
        "questionId": "39bwIB4SSouJ",
        "type": "single",
        "questions": "Have you been a part of any ML Internships at organizations?",
        "dataCapture": "",
        "autoFill": "",
        "category": "General",
        "rows": "",
        "answers": "['Yes', 'No']",
        "answerId": "[\"NRtZ3affwF6h\",\"QCfN5HS1Dv1Z\"]",
        "scores": "[1,0]"
    },
    {
        "questionId": "YVQI4xHytSjT",
        "type": "multiple",
        "questions": "Do you plan to enter the workforce as a Data Scientist, ML engineer, or Data Analyst in the future?  ",
        "dataCapture": "",
        "autoFill": "",
        "category": "General",
        "rows": "",
        "answers": "[Data Scientist, ML Engineer, Data Analyst, other] ",
        "answerId": "[\"WuwI8FpqYX3G\",\"JLTSAVMpHTbb\",\"YJmAjpiXES11\",\"ZC7lNCBhIPY9\"]",
        "scores": "[1,1,1,1]"
    },
    {
        "questionId": "vvL1R3G3rcP4",
        "type": "multiple",
        "questions": "What data types do you prefer to work with on your current projects?",
        "dataCapture": "",
        "autoFill": "",
        "category": "Data Preparation",
        "rows": "",
        "answers": "['Text', 'Numerical', 'Geospatial', 'Images', 'Audio', 'Video', 'Other', 'I do not know']",
        "answerId": "[\"ZFaAY7qqXCSY\",\"HKfhZPuSrnxs\",\"k2UBTiG53WU8\",\"dLO0Y7bTsJdS\",\"IfAJ6IHXToss\",\"wrtdo291qko0\",\"GV1IMO9wuh7a\",\"i9EP7H7VhQyj\"]",
        "scores": "[1,1,1,1,1,1,1,0]"
    },
    {
        "questionId": "sTfUTlgMxTUO",
        "type": "single",
        "questions": "What is the largest dataset that you have interacted with in terms of rows?",
        "dataCapture": "",
        "autoFill": "",
        "category": "Data Preparation",
        "rows": "",
        "answers": "[ Under 5K, 5K-50K, 50K-500K, 1M+, I don't know]",
        "answerId": "[\"TPk0GQvrWqDM\",\"PbfU96cFgQh2\",\"Ts6sbQIKoWOH\",\"GijjjVLy8PjD\",\"cdMeQiijq41H\"]",
        "scores": "[1,2,3,4,0]"
    },
    {
        "questionId": "vNylmAIrBZsX",
        "type": "multiple",
        "questions": "Which IDEs have you worked with to prepare data?  ",
        "dataCapture": "",
        "autoFill": "",
        "category": "Data Preparation",
        "rows": "",
        "answers": "[Jupyter Notebook, SageMaker, Google Colab, GitHub, Other]",
        "answerId": "[\"hY1A9rJVewQs\",\"9S2CaG45aXtU\",\"DG7p6T1rh7TF\",\"NCt9yhn5gfiH\",\"tqcw2DUEndk2\"]",
        "scores": "[1,1,1,1,1]"
    },
    {
        "questionId": "PdpM2Xe0JX6S",
        "type": "single",
        "questions": "Which of the following best describes your aptitude for accessing data?",
        "dataCapture": "",
        "autoFill": "",
        "category": "Data Preparation",
        "rows": "",
        "answers": "['There is a standardized protocol for accessing data across the organization', 'Each department/division constructs its own protocol for accessing data', 'Individuals set up their own protocols for accessing data', 'I do not know']",
        "answerId": "[\"xRLh3DIAsReI\",\"YIQ5VieeMJTk\",\"mimnsn9M6EZO\",\"KRNBqW7yE9v6\"]",
        "scores": "[3,2,1,0]"
    },
    {
        "questionId": "KPs5Wh36sJtm",
        "type": "multiple",
        "questions": "I can, ",
        "dataCapture": "",
        "autoFill": "",
        "category": "Data Preparation",
        "rows": "",
        "answers": "['Integrate internal data between different systems/departments', 'Host/maintain a live data feed', 'Backup and retrieve historical data', 'Ingest data from external sources', 'Query live data', 'None of the above', 'I do not know']",
        "answerId": "[\"ZOyxVFmNvFjf\",\"cKg3Lre9AjRA\",\"gsCO8pnOnL3f\",\"CXXSVFiYOyJ6\",\"KuOlAdMne7js\",\"BKQHZE41OQ1x\",\"jHj2ri8ahdQ2\"]",
        "scores": "[1,1,1,1,1,0,0]"
    },
    {
        "questionId": "WUbPK1cUV163",
        "type": "single",
        "questions": "Have you been part of identifying the problem statement and establish a baseline?",
        "dataCapture": "",
        "autoFill": "",
        "category": "Data Preparation",
        "rows": "",
        "answers": "['Yes' , 'No']",
        "answerId": "[\"Xpc9L1qjtcbv\",\"Wc9xvmDmWcCC\"]",
        "scores": "[1,0]"
    },
    {
        "questionId": "BxOl8NHPgUiS",
        "type": "multiple",
        "questions": "List out the Python libraries/architecture you have had exposure to, for Data Analysis, maching learning and deep learning?",
        "dataCapture": "",
        "autoFill": "",
        "category": "Modeling",
        "rows": "Choose Many",
        "answers": "[SciPy, Pandas, Numpy, Scikit learn, Tensorflow, Pytorch, Transformer, OpenCV, other, none of the above] ",
        "answerId": "[\"YqLAruQFeRB7\",\"GWIBlvFLnRN6\",\"O0ELUOAuYXv7\",\"hqpUO8w0N7fr\",\"ob4Qc9avLkWT\",\"dbwKPDmyJUVw\",\"RQr2Ospf16yE\",\"b2GlY6L9Qkt3\",\"fGy4LSeNuAhl\",\"NtmasmKIfCqD\"]",
        "scores": "[1,1,1,1,1,1,1,1,1,0]"
    },
    {
        "questionId": "YjHwt0UcsaLl",
        "type": "single",
        "questions": "In your coursework, have you developed any models for research through your academic institution or lab work?  If so, how many?  ",
        "dataCapture": "",
        "autoFill": "",
        "category": "Modeling",
        "rows": "",
        "answers": "['0', '1-5', '6-10', '11-15', '16-20', '21+']",
        "answerId": "[\"L4E8093cawNI\",\"AAngk6A79h96\",\"5K3Dyfg8wZ8e\",\"IWb9GWpcsd63\",\"c8YmrjNBjBYq\",\"EKhGTPTI0T4X\"]",
        "scores": "[0,1,2,3,4,5]"
    },
    {
        "questionId": "GL9kmOkWeSlJ",
        "type": "multiple",
        "questions": "Regarding Maching Learning Engineering, have you been exposed to any of these?",
        "dataCapture": "",
        "autoFill": "",
        "category": "Modeling",
        "rows": "",
        "answers": "[Flask, Flink, Snowflake, AWS SageMaker, Kubernetes, Spark, Docker] ",
        "answerId": "[\"NkCTdSxHWMYr\",\"Fw4KnKVa8TJG\",\"DNLuGHwlkax2\",\"bWMtBpLeRftj\",\"mYAHgCPMoIlW\",\"SrgXVFZkeSk6\",\"ElElaGXb8MZ4\"]",
        "scores": "[1,1,1,1,1,1,1]"
    },
    {
        "questionId": "EYVV15tfxNyl",
        "type": "single",
        "questions": "What data visualization tools have you been exposed to?  ",
        "dataCapture": "",
        "autoFill": "",
        "category": "Modeling",
        "rows": "",
        "answers": "[Tableau, Plotly, Matplotlib, Seaborn, Other]",
        "answerId": "[\"gqSqKEKRBmEJ\",\"JeWefJTBJyTy\",\"Bvnwi7Z5h8Fb\",\"1yV47OGCfZ8C\",\"P8BEn7HqFqeF\"]",
        "scores": "[1,1,1,1,1]"
    },
    {
        "questionId": "U4dGGi0VypQ4",
        "type": "multiple",
        "questions": "What kinds of metrics that your machine learning models have used in development?",
        "dataCapture": "",
        "autoFill": "",
        "category": "Modeling",
        "rows": "",
        "answers": "['RMSE', 'R2', 'Accuracy', 'F1', 'Precision', 'Recall', 'ROC_AUC score', 'NDCG', 'Other', 'I do not know']",
        "answerId": "[\"o5KVKsdc2kW6\",\"VB7UgymEHh1N\",\"vH8dPf0fApEj\",\"hy5TJiCsjwSu\",\"LbR2NUIQo3Jy\",\"FiKJxRQXKDro\",\"6VfZSLt55THZ\",\"s3p209xROFB2\",\"R1QAJBfvI9PA\",\"0stVsmt86tIp\"]",
        "scores": "[1,1,1,1,1,1,1,1,1,0]"
    },
    {
        "questionId": "oQfEQV1rp8ju",
        "type": "multiple",
        "questions": "What MLOps coursework would you like to focus on?  ",
        "dataCapture": "",
        "autoFill": "",
        "category": "Modeling",
        "rows": "",
        "answers": "[ API Integration and Documentation, Model Function Testing, Establishing Secure Data Pipelines, Identifying KPIs, Real time inference, Latency Reduction]",
        "answerId": "[\"prWQKBOKtdmF\",\"UIv0jHgZRbSm\",\"QDMCKD3Ll36L\",\"BX9Biht6u2CV\",\"LdU1XUD64EfP\",\"7PoSD4l53aCJ\"]",
        "scores": "[1,1,1,1,1,1]"
    },
    {
        "questionId": "UxgRaTwZxloO",
        "type": "single",
        "questions": "On average, how long does it take for you potentially deploy a model?",
        "dataCapture": "",
        "autoFill": "",
        "category": "Modeling",
        "rows": "",
        "answers": "['Less than 1 week', '1-3 weeks', '4-8 weeks', 'More than 8 weeks', 'I do not know']",
        "answerId": "[\"ZnO21M84QnPw\",\"P1CyIL0AZVLe\",\"31NtU4a7RS3G\",\"4ip78Msfr5Ih\",\"gPyumRXpibhv\"]",
        "scores": "[4,3,2,1,0]"
    },
    {
        "questionId": "55DFJywhn65X",
        "type": "single",
        "questions": "Which particular ML lifecycle appeals to you most?  ",
        "dataCapture": "",
        "autoFill": "",
        "category": "Modeling",
        "rows": "",
        "answers": "[ Data Preparation, Model Development and Testing, Model Deployment, Model Monitoring, or Assessing Business Value using ML]",
        "answerId": "[\"Zv6xujqk7dHx\",\"xPnCxby1kQse\",\"VP0UTJuVrHK8\",\"9UPl7j9m36Zf\",\"lm2GhXMJmPY5\"]",
        "scores": "[1,1,1,1,1]"
    },
    {
        "questionId": "lGP6FRea7AWZ",
        "type": "single",
        "questions": "Does your current academic institution offer specific model monitoring coursework?",
        "dataCapture": "",
        "autoFill": "",
        "category": "Modeling",
        "rows": "Expand?",
        "answers": "[ Yes, Not currently]",
        "answerId": "[\"Dcw05XWlmFmw\",\"TrVW9OvJwTsY\"]",
        "scores": "[1,0]"
    },
    {
        "questionId": "uHGKjnUglGfO",
        "type": "multiple",
        "questions": "What types of ML Applications are you most interested in?  ",
        "dataCapture": "",
        "autoFill": "",
        "category": "Career Trajectory",
        "rows": "",
        "answers": "[Predictive Analysis, Anamoly Detection, NLP, Computer Vision, Deep Learning, Robotics, Other]",
        "answerId": "[\"gCGRs7qw449c\",\"DTbW5x4JmAyn\",\"rJ7iwPwimaYC\",\"sP8IFgjr7IiE\",\"tap4BrlJnXcf\",\"K0WcYB6rn0qH\",\"bq7dy6MpeUJq\"]",
        "scores": "[1,1,1,1,1,1,1]"
    },
    {
        "questionId": "JD8S0C4FBbmx",
        "type": "single",
        "questions": "In your opinion, which area of the ML Lifecycle offers the greatest value for ML?  ",
        "dataCapture": "",
        "autoFill": "",
        "category": "Career Trajectory",
        "rows": "",
        "answers": "[Data Preparation, Model Development, Model Deployment, Model Monitoring, or Business Value, I don't know]",
        "answerId": "[\"M4knO3NsITBR\",\"iuddbLnQnwqD\",\"O8nNd0woGYB1\",\"lXg3sIGJ5DAo\",\"wKNK6aLPTdB9\",\"oEuV9vNPxqEr\"]",
        "scores": "[1,1,1,1,1,0]"
    },
    {
        "questionId": "ZINnWmohLAWU",
        "type": "multiple",
        "questions": "Do you have ML related career goal? If yes then what is it?",
        "dataCapture": "",
        "autoFill": "",
        "category": "Career Trajectory",
        "rows": "",
        "answers": "[Machine learning engineer, MLOps and Deployment, Computer vision / NLP / computational linguistics specialists, Data Scientist, I don't know]",
        "answerId": "[\"h4Iq0ADrELlC\",\"2FWv9nIysg0q\",\"XrQRZs8kTOfW\",\"bRcE8X34g0LW\",\"yRNEhC9ZSW9X\"]",
        "scores": "[1,1,1,1,0]"
    },
    {
        "questionId": "PQ0KD0TObc6Q",
        "type": "multiple",
        "questions": "What have you learned/are you planning to learn for a career in machine learning?",
        "dataCapture": "",
        "autoFill": "",
        "category": "Career Trajectory",
        "rows": "",
        "answers": "['Programming in Python/C++/Java and corresponding ML libraries/frameworks', 'Statistical Analysis with R', 'Data wrangling with Pandas and Numpy', 'Deep learning, neural network principles and engineering frameworks with Tensorflow and PyTorch', 'Deployment tools like AWS SageMaker', 'I don't know']",
        "answerId": "[\"tWkxy0rm0hi9\",\"rAp4l3vQc48K\",\"UxTjMg5KaSWP\",\"H13JcUhqI7Yi\",\"yjnTfVNShBOw\",\"bx4u26ThFtso\",\"Pfrs0bsWJD6O\"]",
        "scores": "[1,1,1,1,1,0]"
    },
    {
        "questionId": "iofeAB4hyRhC",
        "type": "multiple",
        "questions": "Has your academic institution considered doing these following things for your career development?",
        "dataCapture": "",
        "autoFill": "",
        "category": "Career Trajectory",
        "rows": "",
        "answers": "['Resume building', 'Practice your learning by working on real world projects', 'Compete on some platforms like Kaggle', 'Interview preparation', 'None of Above']",
        "answerId": "[\"qHDr9LWuNA7M\",\"wP6a5vmbROFc\",\"NWfnSaWM0bjw\",\"btQAoiYdjXJB\",\"bngQImdyoIBV\"]",
        "scores": "[1,1,1,1,0]"
    },
    {
        "questionId": "XtEfERdmXBrA",
        "type": "multiple",
        "questions": "What leadership styles that you most identified with?",
        "dataCapture": "",
        "autoFill": "",
        "category": "Career Trajectory",
        "rows": "",
        "answers": "[Transactional', 'Democratic,' Transformational, 'Servant,' 'Charasmatic,']",
        "answerId": "[\"u3kQ3KrHbPDs\",\"x7JIELhL9jSD\",\"ZKJhVFGXTaWv\",\"5dSB9ECVAv52\",\"u94Pk9RiS8qe\",\"R9qWSCmEsiB8\"]",
        "scores": "[1,1,1,2,1]"
    },
    {
        "questionId": "BxCnIp3SVvWq",
        "type": "single",
        "questions": "How do we perform Bayesian classification when some features are missing?",
        "dataCapture": "",
        "autoFill": "",
        "category": "ML Aptitude",
        "rows": "",
        "answers": "['We assuming the missing values as the mean of all values.', 'We ignore the missing features.', 'We integrate the posteriors probabilities over the missing features.', 'Drop the features completely if most of the entries are missing.']",
        "answerId": "[\"5erluRNAU7Qd\",\"gpMbvfYBKX8U\",\"mMtLT3aYvlx7\",\"LwY5l8JkJCh6\"]",
        "scores": "[0, 0, 1, 0.5]"
    },
    {
        "questionId": "JFjYKyW80pal",
        "type": "single",
        "questions": "The robotic arm will be able to paint every corner in the automotive parts while minimizing the quantity of paint wasted in the process. Which learning technique is used in this problem?",
        "dataCapture": "",
        "autoFill": "",
        "category": "ML Aptitude",
        "rows": "",
        "answers": "['Supervised Learning', 'Unsupervised Learning', 'Both Supervised and Unsupervised Learning', 'Reinforcement Learning']",
        "answerId": "[\"AnxOOpRAKqBc\",\"Nt5n4TUmRoto\",\"ju0qYqQFmjXe\",\"apD5tjCXr2E3\"]",
        "scores": "[0, 0, 0, 1]"
    },
    {
        "questionId": "IIYw2nJ3HkXx",
        "type": "multiple",
        "questions": "What kind of distance metric(s) are suitable for categorical variables to find the closest neighbors?",
        "dataCapture": "",
        "autoFill": "",
        "category": "ML Aptitude",
        "rows": "",
        "answers": "['Euclidean distance', 'Manhattan distance', 'Minkowski distance', 'Hamming Distance']",
        "answerId": "[\"wGQm480inr9o\",\"AwinHtlnxGlX\",\"bD0oAE8CQi0T\",\"DUGAfNCFWaKu\"]",
        "scores": "[0, 0, 0, 1]"
    },
    {
        "questionId": "mJ54c4BIljBI",
        "type": "single",
        "questions": "Which of the following is FALSE about Correlation and Covariance?",
        "dataCapture": "",
        "autoFill": "",
        "category": "ML Aptitude",
        "rows": "",
        "answers": "['A zero correlation does not necessarily imply independence between variables', 'Correlation and covariance values are the same', 'The covariance and correlation are always the same sign', 'Correlation is the standardized version of Covariance']",
        "answerId": "[\"WZlVF7OxQVqd\",\"1TgUERuhhofg\",\"ceyi3e0b7fUi\",\"Latp0HyZAWKM\"]",
        "scores": "[0,1,0,0]"
    },
    {
        "questionId": "g0XPtsTXsGIC",
        "type": "single",
        "questions": "Which of the following is FALSE about Deep Learning and Machine Learning algorithms?",
        "dataCapture": "",
        "autoFill": "",
        "category": "ML Aptitude",
        "rows": "",
        "answers": "['Deep Learning algorithms work efficiently on a high amount of data','Feature Extraction needs to be done manually in both ML and DL algorithms', ' Deep Learning algorithms are best suited for unstructured data', 'Deep Learning algorithms require high computational power']",
        "answerId": "[\"V9kAJnb8ySa5\",\"1Q33ZZDe480t\",\"C7js3UiGgcs4\",\"2CljIRiovKxx\"]",
        "scores": "[0,1,0,0]"
    },
    {
        "questionId": "QE3vKB2absKV",
        "type": "single",
        "questions": "Do you think your Academic Institution puts enogh emphasis on the business value of Machine Learning?",
        "dataCapture": "",
        "autoFill": "",
        "category": "Business Value",
        "rows": "",
        "answers": "['Yes', 'No', 'I do not know']",
        "answerId": "[\"GQQtobkNEn7M\",\"GStj0YMaXfb6\",\"OQ082gXyXS7R\"]",
        "scores": "[1,0,0]"
    },
    {
        "questionId": "jfqxgwF2Figm",
        "type": "single",
        "questions": "If there was a course on business value using ML, would that prompt a different career trajactory?  ",
        "dataCapture": "",
        "autoFill": "",
        "category": "Business Value",
        "rows": "",
        "answers": "[Yes, No, I do not know']",
        "answerId": "[\"Vd4kMaFlGFvk\",\"nZF8Qy9cuqEG\",\"mnO3vxlHqq14\"]",
        "scores": "[1,1,0]"
    },
    {
        "questionId": "6GxeMycoCHoG",
        "type": "single",
        "questions": "How important is machine learning for your overall career path?",
        "dataCapture": "",
        "autoFill": "",
        "category": "Business Value",
        "rows": "",
        "answers": "['Not important at all', 'Slightly important', 'Somewhat important', 'Important', 'Very important']",
        "answerId": "[\"Go5sBmslUUAo\",\"0maXdGdUaiFX\",\"P0eYQfFfV1N7\",\"uACKqcJj5DpM\",\"WdMjmEgs0bDN\"]",
        "scores": "[0,1,2,3,4]"
    },
    {
        "questionId": "QxYMQmeNVCKh",
        "type": "multiple",
        "questions": "Please identify any experience you've had aligning business objectives with machine learning models.",
        "dataCapture": "",
        "autoFill": "",
        "category": "Business Value",
        "rows": "",
        "answers": "['The data we need is not available', 'We have no models to align our objectives with', 'We do not have the staff to align machine learning models with business objectives', 'We do not have the resources to align machine learning models with business objectives', 'Other']",
        "answerId": "[\"fWwF1lhp2iO0\",\"QeYsKLZKtkrV\",\"FKQYE1mguWH5\",\"cwFAxID9cudl\",\"RhLJEHpMfIgK\"]",
        "scores": ""
    },
    {
        "questionId": "pZoxfwQcWFC9",
        "type": "multiple",
        "questions": "What has been the most challenging aspect(s) of using machine learning models?",
        "dataCapture": "",
        "autoFill": "",
        "category": "General",
        "rows": "",
        "answers": "['Not enough data', 'Low data quality', 'Data centralization', 'Lack of technical talent', 'Limited budget', 'Deployment of models or results', 'Developing a strategy for use', 'Labeling data', 'I do not know']",
        "answerId": "[\"aDXSl8RsAQm6\",\"12k8H4lySEU4\",\"UT52yVvGLMyu\",\"DYhS0jUNBJ1J\",\"xwQBpdJUqv3I\",\"Ga1La39A34Hj\",\"kiR0mLmMshqN\",\"3IK82GX1UNV2\",\"n6gNjLWJxnJJ\"]",
        "scores": ""
    },
    {
        "questionId": "JaKyEiVBYNGF",
        "type": "multiple",
        "questions": "What has been the most rewarding aspect(s) of using machine learning models?",
        "dataCapture": "",
        "autoFill": "",
        "category": "General",
        "rows": "",
        "answers": "['Enhanced efficiency', 'Improved operations', 'Improved decision-making abilities', 'New streams of revenue', 'Improved revenue streams', 'I do not know']",
        "answerId": "[\"RMIStm3aFuKg\",\"hHpSnXOEBVeo\",\"1p8ZavN8Ov8j\",\"EFyErGQZaP86\",\"FgXOBm4AO0QU\",\"96ZkhFDm6DUs\"]",
        "scores": ""
    },
    {
        "questionId": "C7XucjtCtMEQ",
        "type": "multiple",
        "questions": "How did you solve the challenge(s) you identified?",
        "dataCapture": "",
        "autoFill": "",
        "category": "General",
        "rows": "",
        "answers": "['Developed an internal solution', 'Outsourced the solution', 'It has not been solved yet']",
        "answerId": "[\"GsPueu2RyD11\",\"JQ5n1yAxSjnj\",\"vdoBLKWvDTB8\"]",
        "scores": "[1,0.5,0]"
    },
    {
        "questionId": "AnRWtI3LEqbF",
        "type": "single",
        "questions": "###NAME, would you be willing to take our survey again in 4 months?",
        "dataCapture": "",
        "autoFill": "",
        "category": "General",
        "rows": "",
        "answers": "['Yes', 'No']",
        "answerId": "[\"Hja08wTQBYEP\",\"nww9GScQL2Qd\"]",
        "scores": ""
    },
    {
        "questionId": "u5jviSDhQbBt",
        "type": "open",
        "questions": "What is the best email for the person who would be most knowledgable about machine learning at your company?",
        "dataCapture": "",
        "autoFill": "",
        "category": "General",
        "rows": "",
        "answers": "[]",
        "answerId": "[\"3njgg6Huqumq\"]",
        "scores": ""
    }
]

const newFrozen = [
    {
        "questionId": "sy9SkVGXW9f1",
        "type": "open",
        "questions": "What is your first name?",
        "promptName": "",
        "buttonText": "",
        "category": "General",
        "rows": "",
        "answers": "[]",
        "answerId": "[\"7a8LfLIMdEy6\"]",
        "dataCapture": "NAME",
        "autoFill": "name"
    },
    {
        "questionId": "ktGqfhk10tZQ",
        "type": "single",
        "questions": "What is your current student designation?",
        "promptName": "",
        "buttonText": "",
        "category": "General",
        "rows": "",
        "answers": "[Freshman, Sophomore, Junior, Senior, Graduate Level, Other]",
        "answerId": "[\"Cy56yNoP1SeI\",\"ZHpeNF2qSKuT\",\"uegJeAKkgN6X\",\"LXcdWaf6eRom\",\"LaBilnZqtBlP\",\"IrH7EFky6Wlg\"]",
        "dataCapture": "DESIGNATION",
        "autoFill": "designation"
    },
    {
        "questionId": "3RkTh825aRsT",
        "type": "single",
        "questions": "Is your major STEM? (Science, Technology, Engineering and Mathematics)",
        "promptName": "",
        "buttonText": "",
        "category": "General",
        "rows": "",
        "answers": "[Yes, No]",
        "answerId": "[\"ARkOogKhls8m\",\"lxlI88NrGIFq\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "U25qKAuGMkZm",
        "type": "single",
        "questions": "What's your current GPA?",
        "promptName": "",
        "buttonText": "",
        "category": "General",
        "rows": "",
        "answers": "[above 3.5, 3-3.5, below 3]",
        "answerId": "[\"CcnuIc0qhMKF\",\"WG7jCVGksL7b\",\"4NkkGXhXXhB5\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "BNOQH2CfYkar",
        "type": "open",
        "questions": "###NAME, what is your email?",
        "promptName": "",
        "buttonText": "",
        "category": "General",
        "rows": "",
        "answers": "[]",
        "answerId": "[\"x7biuF0npcY3\"]",
        "dataCapture": "EMAIL",
        "autoFill": "email"
    },
    {
        "questionId": "Kb6TTYeDpTpH",
        "type": "single",
        "questions": "Which best describes your level of interest in Machine Learning?",
        "promptName": "",
        "buttonText": "",
        "category": "General",
        "rows": "",
        "answers": "['Long term career goal', 'Personal interest', 'Hobby', 'I don't know']",
        "answerId": "[\"kadbCNHKSSjg\",\"EW1vZthJsoDc\",\"COEWW87I19ee\",\"f7igtkZXJAyj\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "vQkpEkv9nvE1",
        "type": "single",
        "questions": "Can you describe your level of exposure to Machine Learning",
        "promptName": "",
        "buttonText": "",
        "category": "General",
        "rows": "",
        "answers": "[Exploratory, Observer, Enthusiast, Passionate, I don't know]",
        "answerId": "[\"gBpsH0kc0I1i\",\"1dXm2r7THrI2\",\"ryQuEeR7ArT7\",\"kWOQa3P6G1Te\",\"6gurjoqd3PSx\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "",
        "type": "prompt",
        "questions": "Let's discuss your achievements in ML so far",
        "promptName": "achievements",
        "buttonText": "Ok",
        "category": "General",
        "rows": "",
        "answers": "[]",
        "answerId": "[\"utMHxAAUvsp8\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "QrH3MPbcM4jJ",
        "type": "single",
        "questions": "How many online ML certifications have you been awarded?",
        "promptName": "",
        "buttonText": "",
        "category": "General",
        "rows": "",
        "answers": "[None, 1-3, 4-6, 7-9, above 9]",
        "answerId": "[\"NkJ8UgdPqcEX\",\"K2E9gcCa5oxE\",\"5FsCPeqIGCZf\",\"ak9LpRqfso5w\",\"4WG1Sfct4xEy\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "39bwIB4SSouJ",
        "type": "single",
        "questions": "Have you been a part of any ML Internships at organizations?",
        "promptName": "",
        "buttonText": "",
        "category": "General",
        "rows": "",
        "answers": "['Yes', 'No']",
        "answerId": "[\"NRtZ3affwF6h\",\"QCfN5HS1Dv1Z\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "YVQI4xHytSjT",
        "type": "multiple",
        "questions": "Do you plan to enter the workforce as a Data Scientist, ML engineer, or Data Analyst in the future?",
        "promptName": "",
        "buttonText": "",
        "category": "General",
        "rows": "",
        "answers": "[Data Scientist, ML Engineer, Data Analyst, other] ",
        "answerId": "[\"WuwI8FpqYX3G\",\"JLTSAVMpHTbb\",\"YJmAjpiXES11\",\"ZC7lNCBhIPY9\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "vvL1R3G3rcP4",
        "type": "multiple",
        "questions": "What data types do you prefer to work with on your current projects?",
        "promptName": "",
        "buttonText": "",
        "category": "Data Preparation",
        "rows": "",
        "answers": "['Text', 'Numerical', 'Geospatial', 'Images', 'Audio', 'Video', 'Other', 'I do not know']",
        "answerId": "[\"ZFaAY7qqXCSY\",\"HKfhZPuSrnxs\",\"k2UBTiG53WU8\",\"dLO0Y7bTsJdS\",\"IfAJ6IHXToss\",\"wrtdo291qko0\",\"GV1IMO9wuh7a\",\"i9EP7H7VhQyj\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "sTfUTlgMxTUO",
        "type": "single",
        "questions": "What is the largest dataset that you have interacted with in terms of features?",
        "promptName": "",
        "buttonText": "",
        "category": "Data Preparation",
        "rows": "",
        "answers": "[ Under 50, 100-500, 500-1K, 1K-5K, over 5K, I don't know]",
        "answerId": "[\"TPk0GQvrWqDM\",\"PbfU96cFgQh2\",\"Ts6sbQIKoWOH\",\"GijjjVLy8PjD\",\"cdMeQiijq41H\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "vNylmAIrBZsX",
        "type": "multiple",
        "questions": "Which IDEs have you worked with to prepare data?",
        "promptName": "",
        "buttonText": "",
        "category": "Data Preparation",
        "rows": "",
        "answers": "[Jupyter, SageMaker, Google Colab, Spyder, Pycharm, Other]",
        "answerId": "[\"hY1A9rJVewQs\",\"9S2CaG45aXtU\",\"DG7p6T1rh7TF\",\"NCt9yhn5gfiH\",\"tqcw2DUEndk2\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "PdpM2Xe0JX6S",
        "type": "single",
        "questions": "Which of the following best describes your aptitude for accessing data?",
        "promptName": "",
        "buttonText": "",
        "category": "Data Preparation",
        "rows": "",
        "answers": "['There is a standardized protocol for accessing data across the organization', 'Each department/division constructs its own protocol for accessing data', 'Individuals set up their own protocols for accessing data', 'I do not know']",
        "answerId": "[\"xRLh3DIAsReI\",\"YIQ5VieeMJTk\",\"mimnsn9M6EZO\",\"KRNBqW7yE9v6\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "KPs5Wh36sJtm",
        "type": "multiple",
        "questions": "Regarding Data Preparation, I have the ability to:  ",
        "promptName": "",
        "buttonText": "",
        "category": "Data Preparation",
        "rows": "",
        "answers": "['Integrate internal data between different systems/departments', 'Host/maintain a live data feed', 'Backup and retrieve historical data', 'Ingest or introduce data from external sources', 'Query live data', 'None of the above', 'I do not know']",
        "answerId": "[\"ZOyxVFmNvFjf\",\"cKg3Lre9AjRA\",\"gsCO8pnOnL3f\",\"CXXSVFiYOyJ6\",\"KuOlAdMne7js\",\"BKQHZE41OQ1x\",\"jHj2ri8ahdQ2\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "WUbPK1cUV163",
        "type": "single",
        "questions": "Have you been part of identifying the problem statement and establish a baseline?",
        "promptName": "",
        "buttonText": "",
        "category": "Data Preparation",
        "rows": "",
        "answers": "['Yes' , 'No']",
        "answerId": "[\"Xpc9L1qjtcbv\",\"Wc9xvmDmWcCC\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "BxOl8NHPgUiS",
        "type": "multiple",
        "questions": "List out the Python libraries/architecture you have had exposure to, for Data Analysis, maching learning and deep learning?",
        "promptName": "",
        "buttonText": "",
        "category": "Modeling",
        "rows": "",
        "answers": "[SciPy, Pandas, Numpy, Scikit learn, Tensorflow, Pytorch, Transformer, OpenCV, other, none of the above] ",
        "answerId": "[\"YqLAruQFeRB7\",\"GWIBlvFLnRN6\",\"O0ELUOAuYXv7\",\"hqpUO8w0N7fr\",\"ob4Qc9avLkWT\",\"dbwKPDmyJUVw\",\"RQr2Ospf16yE\",\"b2GlY6L9Qkt3\",\"fGy4LSeNuAhl\",\"NtmasmKIfCqD\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "YjHwt0UcsaLl",
        "type": "single",
        "questions": "In your coursework, have you developed any models for research through your academic institution or lab work?  If so, how many?",
        "promptName": "",
        "buttonText": "",
        "category": "Modeling",
        "rows": "",
        "answers": "['0', '1-5', '6-10', '11-15', '16-20', '21+']",
        "answerId": "[\"L4E8093cawNI\",\"AAngk6A79h96\",\"5K3Dyfg8wZ8e\",\"IWb9GWpcsd63\",\"c8YmrjNBjBYq\",\"EKhGTPTI0T4X\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "GL9kmOkWeSlJ",
        "type": "multiple",
        "questions": "Regarding Maching Learning Engineering, have you been exposed to any of these?",
        "promptName": "",
        "buttonText": "",
        "category": "Modeling",
        "rows": "",
        "answers": "[Flask, Flink, Snowflake, AWS SageMaker, Kubernetes, Spark, Docker] ",
        "answerId": "[\"NkCTdSxHWMYr\",\"Fw4KnKVa8TJG\",\"DNLuGHwlkax2\",\"bWMtBpLeRftj\",\"mYAHgCPMoIlW\",\"SrgXVFZkeSk6\",\"ElElaGXb8MZ4\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "EYVV15tfxNyl",
        "type": "multiple",
        "questions": "What data visualization tools have you been exposed to?",
        "promptName": "",
        "buttonText": "",
        "category": "Modeling",
        "rows": "",
        "answers": "[Tableau, Plotly, Matplotlib, Seaborn, Other]",
        "answerId": "[\"gqSqKEKRBmEJ\",\"JeWefJTBJyTy\",\"Bvnwi7Z5h8Fb\",\"1yV47OGCfZ8C\",\"P8BEn7HqFqeF\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "U4dGGi0VypQ4",
        "type": "multiple",
        "questions": "What type of accuracy metrics were your machine learning models exposed to?",
        "promptName": "",
        "buttonText": "",
        "category": "Modeling",
        "rows": "",
        "answers": "['RMSE', 'R2', 'Accuracy', 'F1', 'Precision', 'Recall', 'ROC_AUC score', 'NDCG', 'Other', 'I do not know']",
        "answerId": "[\"o5KVKsdc2kW6\",\"VB7UgymEHh1N\",\"vH8dPf0fApEj\",\"hy5TJiCsjwSu\",\"LbR2NUIQo3Jy\",\"FiKJxRQXKDro\",\"6VfZSLt55THZ\",\"s3p209xROFB2\",\"R1QAJBfvI9PA\",\"0stVsmt86tIp\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "oQfEQV1rp8ju",
        "type": "multiple",
        "questions": "What MLOps coursework would you like to focus on?",
        "promptName": "",
        "buttonText": "",
        "category": "Modeling",
        "rows": "",
        "answers": "[ API Integration and Documentation, Model Function Testing, Establishing Secure Data Pipelines, Identifying KPIs, Real time inference, Latency Reduction]",
        "answerId": "[\"prWQKBOKtdmF\",\"UIv0jHgZRbSm\",\"QDMCKD3Ll36L\",\"BX9Biht6u2CV\",\"LdU1XUD64EfP\",\"7PoSD4l53aCJ\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "UxgRaTwZxloO",
        "type": "single",
        "questions": "On average, how long does it take for you to deploy a model once tested and trained?",
        "promptName": "",
        "buttonText": "",
        "category": "Modeling",
        "rows": "",
        "answers": "['Less than 1 week', '1-3 weeks', '4-8 weeks', 'More than 8 weeks', 'I do not know']",
        "answerId": "[\"ZnO21M84QnPw\",\"P1CyIL0AZVLe\",\"31NtU4a7RS3G\",\"4ip78Msfr5Ih\",\"gPyumRXpibhv\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "55DFJywhn65X",
        "type": "single",
        "questions": "Which particular ML lifecycle appeals to you most?",
        "promptName": "",
        "buttonText": "",
        "category": "Modeling",
        "rows": "",
        "answers": "[ Data Preparation, Model Development and Testing, Model Deployment, Model Monitoring, or Assessing Business Value using ML]",
        "answerId": "[\"Zv6xujqk7dHx\",\"xPnCxby1kQse\",\"VP0UTJuVrHK8\",\"9UPl7j9m36Zf\",\"lm2GhXMJmPY5\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "lGP6FRea7AWZ",
        "type": "single",
        "questions": "Does your current academic institution offer specific model monitoring coursework?",
        "promptName": "",
        "buttonText": "",
        "category": "Modeling",
        "rows": "",
        "answers": "[ Yes, Not currently]",
        "answerId": "[\"Dcw05XWlmFmw\",\"TrVW9OvJwTsY\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "uHGKjnUglGfO",
        "type": "multiple",
        "questions": "What types of ML Applications are you most interested in?",
        "promptName": "",
        "buttonText": "",
        "category": "Career Trajectory",
        "rows": "",
        "answers": "[Predictive Analysis, Anamoly Detection, NLP, Computer Vision, Deep Learning, Robotics, Other]",
        "answerId": "[\"gCGRs7qw449c\",\"DTbW5x4JmAyn\",\"rJ7iwPwimaYC\",\"sP8IFgjr7IiE\",\"tap4BrlJnXcf\",\"K0WcYB6rn0qH\",\"bq7dy6MpeUJq\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "JD8S0C4FBbmx",
        "type": "single",
        "questions": "In your opinion, which area of the ML Lifecycle offers the greatest value for ML?",
        "promptName": "",
        "buttonText": "",
        "category": "Career Trajectory",
        "rows": "",
        "answers": "[Data Preparation, Model Development, Model Deployment, Model Monitoring, or Business Value, I don't know]",
        "answerId": "[\"M4knO3NsITBR\",\"iuddbLnQnwqD\",\"O8nNd0woGYB1\",\"lXg3sIGJ5DAo\",\"wKNK6aLPTdB9\",\"oEuV9vNPxqEr\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "ZINnWmohLAWU",
        "type": "multiple",
        "questions": "Do you have ML related career goal? If yes then what is it?",
        "promptName": "",
        "buttonText": "",
        "category": "Career Trajectory",
        "rows": "",
        "answers": "[Machine learning engineer, MLOps and Deployment, Computer vision / NLP / computational linguistics specialists, Data Scientist, I don't know]",
        "answerId": "[\"h4Iq0ADrELlC\",\"2FWv9nIysg0q\",\"XrQRZs8kTOfW\",\"bRcE8X34g0LW\",\"yRNEhC9ZSW9X\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "PQ0KD0TObc6Q",
        "type": "multiple",
        "questions": "What have you learned/are you planning to learn for a career in machine learning?",
        "promptName": "",
        "buttonText": "",
        "category": "Career Trajectory",
        "rows": "",
        "answers": "['Programming in Python/C++/Java and corresponding ML libraries/frameworks', 'Statistical Analysis with R', 'Data wrangling with Pandas and Numpy', 'Deep learning, neural network principles and engineering frameworks with Tensorflow and PyTorch', 'Deployment tools like AWS SageMaker', 'I don't know']",
        "answerId": "[\"tWkxy0rm0hi9\",\"rAp4l3vQc48K\",\"UxTjMg5KaSWP\",\"H13JcUhqI7Yi\",\"yjnTfVNShBOw\",\"bx4u26ThFtso\",\"Pfrs0bsWJD6O\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "iofeAB4hyRhC",
        "type": "multiple",
        "questions": "Has your academic institution considered doing these following things for your career development?",
        "promptName": "",
        "buttonText": "",
        "category": "Career Trajectory",
        "rows": "",
        "answers": "['Resume building', 'Practice your learning by working on real world projects', 'Compete on some platforms like Kaggle', 'Interview preparation', 'None of Above']",
        "answerId": "[\"qHDr9LWuNA7M\",\"wP6a5vmbROFc\",\"NWfnSaWM0bjw\",\"btQAoiYdjXJB\",\"bngQImdyoIBV\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "XtEfERdmXBrA",
        "type": "multiple",
        "questions": "What leadership styles do you most identify with?",
        "promptName": "",
        "buttonText": "",
        "category": "Career Trajectory",
        "rows": "",
        "answers": "[Transactional, Democratic, Transformational, Servant, Charismatic]",
        "answerId": "[\"u3kQ3KrHbPDs\",\"x7JIELhL9jSD\",\"ZKJhVFGXTaWv\",\"5dSB9ECVAv52\",\"u94Pk9RiS8qe\",\"R9qWSCmEsiB8\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "",
        "type": "prompt",
        "questions": "Now we are going to ask a couple questions which will help us better understand your aptitude in ML",
        "promptName": "assessment",
        "buttonText": "Let's go!",
        "category": "",
        "rows": "",
        "answers": "",
        "answerId": "",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "BxCnIp3SVvWq",
        "type": "single",
        "questions": "How do we perform Bayesian classification when some features are missing?",
        "promptName": "",
        "buttonText": "",
        "category": "ML Aptitude",
        "rows": "",
        "answers": "['We assume the missing values as the mean of all values.', 'We ignore the missing features.', 'We integrate the posteriors probabilities over the missing features.', 'Drop the features completely if most of the entries are missing.']",
        "answerId": "[\"5erluRNAU7Qd\",\"gpMbvfYBKX8U\",\"mMtLT3aYvlx7\",\"LwY5l8JkJCh6\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "JFjYKyW80pal",
        "type": "single",
        "questions": "The robotic arm will be able to paint every corner in the automotive parts while minimizing the quantity of paint wasted in the process. Which learning technique is used in this problem?",
        "promptName": "",
        "buttonText": "",
        "category": "ML Aptitude",
        "rows": "",
        "answers": "['Supervised Learning', 'Unsupervised Learning', 'Both Supervised and Unsupervised Learning', 'Reinforcement Learning']",
        "answerId": "[\"AnxOOpRAKqBc\",\"Nt5n4TUmRoto\",\"ju0qYqQFmjXe\",\"apD5tjCXr2E3\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "IIYw2nJ3HkXx",
        "type": "multiple",
        "questions": "What kind of distance metric(s) are suitable for categorical variables to find the closest neighbors?",
        "promptName": "",
        "buttonText": "",
        "category": "ML Aptitude",
        "rows": "",
        "answers": "['Euclidean distance', 'Manhattan distance', 'Minkowski distance', 'Hamming Distance']",
        "answerId": "[\"wGQm480inr9o\",\"AwinHtlnxGlX\",\"bD0oAE8CQi0T\",\"DUGAfNCFWaKu\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "mJ54c4BIljBI",
        "type": "single",
        "questions": "Which of the following is FALSE about Correlation and Covariance?",
        "promptName": "",
        "buttonText": "",
        "category": "ML Aptitude",
        "rows": "",
        "answers": "['A zero correlation does not necessarily imply independence between variables', 'Correlation and covariance values are the same', 'The covariance and correlation are always the same sign', 'Correlation is the standardized version of Covariance']",
        "answerId": "[\"WZlVF7OxQVqd\",\"1TgUERuhhofg\",\"ceyi3e0b7fUi\",\"Latp0HyZAWKM\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "g0XPtsTXsGIC",
        "type": "single",
        "questions": "Which of the following is FALSE about Deep Learning and Machine Learning algorithms?",
        "promptName": "",
        "buttonText": "",
        "category": "ML Aptitude",
        "rows": "",
        "answers": "['Deep Learning algorithms work efficiently on a high amount of data','Feature Extraction needs to be done manually in both ML and DL algorithms', ' Deep Learning algorithms are best suited for unstructured data', 'Deep Learning algorithms require high computational power']",
        "answerId": "[\"V9kAJnb8ySa5\",\"1Q33ZZDe480t\",\"C7js3UiGgcs4\",\"2CljIRiovKxx\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "",
        "type": "prompt",
        "questions": "Thanks for that ###NAME, now let's finish up with the last of your self assessment questions",
        "promptName": "finishUp",
        "buttonText": "onwards",
        "category": "",
        "rows": "",
        "answers": "",
        "answerId": "",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "QE3vKB2absKV",
        "type": "single",
        "questions": "Do you think your Academic Institution puts enough emphasis on the business value of Machine Learning? ",
        "promptName": "",
        "buttonText": "",
        "category": "Business Value",
        "rows": "",
        "answers": "['Yes', 'No', 'I do not know']",
        "answerId": "[\"GQQtobkNEn7M\",\"GStj0YMaXfb6\",\"OQ082gXyXS7R\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "jfqxgwF2Figm",
        "type": "single",
        "questions": "If there was a course on business value using ML, would that prompt a different career trajactory?  ",
        "promptName": "",
        "buttonText": "",
        "category": "Business Value",
        "rows": "",
        "answers": "[Yes, No, I do not know']",
        "answerId": "[\"Vd4kMaFlGFvk\",\"nZF8Qy9cuqEG\",\"mnO3vxlHqq14\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "6GxeMycoCHoG",
        "type": "single",
        "questions": "How important is machine learning for your overall career path? ",
        "promptName": "",
        "buttonText": "",
        "category": "Business Value",
        "rows": "",
        "answers": "['Not important at all', 'Slightly important', 'Somewhat important', 'Important', 'Very important']",
        "answerId": "[\"Go5sBmslUUAo\",\"0maXdGdUaiFX\",\"P0eYQfFfV1N7\",\"uACKqcJj5DpM\",\"WdMjmEgs0bDN\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "QxYMQmeNVCKh",
        "type": "multiple",
        "questions": "Please identify any experience you've had aligning business objectives with machine learning models.",
        "promptName": "",
        "buttonText": "",
        "category": "Business Value",
        "rows": "",
        "answers": "['The data we need is not available', 'We have no models to align our objectives with', 'We do not have the staff to align machine learning models with business objectives', 'We do not have the resources to align machine learning models with business objectives', 'We do not have the staff to align machine learning models with business objectives', 'We do not have the resources to align machine learning models with business objectives',We have identified case studies and research to generate sound models’, Other]",
        "answerId": "[\"fWwF1lhp2iO0\",\"QeYsKLZKtkrV\",\"FKQYE1mguWH5\",\"cwFAxID9cudl\",\"RhLJEHpMfIgK\", \"CB0DhTT0x9JK\", \"kWoMhqVtTSVJ\", \"y2feVxnBIes5\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "pZoxfwQcWFC9",
        "type": "multiple",
        "questions": "What has been the most challenging aspect(s) of using machine learning models?",
        "promptName": "",
        "buttonText": "",
        "category": "General",
        "rows": "",
        "answers": "['Not enough data', 'Low data quality', 'Data centralization', 'Lack of technical talent', 'Limited budget', 'Deployment of models or results', 'Developing a strategy for use', 'Labeling data', 'I do not know']",
        "answerId": "[\"aDXSl8RsAQm6\",\"12k8H4lySEU4\",\"UT52yVvGLMyu\",\"DYhS0jUNBJ1J\",\"xwQBpdJUqv3I\",\"Ga1La39A34Hj\",\"kiR0mLmMshqN\",\"3IK82GX1UNV2\",\"n6gNjLWJxnJJ\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "JaKyEiVBYNGF",
        "type": "multiple",
        "questions": "What has been the most rewarding aspect(s) of using machine learning models?",
        "promptName": "",
        "buttonText": "",
        "category": "General",
        "rows": "",
        "answers": "['Enhanced efficiency', 'Improved operations', 'Improved decision-making abilities', 'New streams of revenue', 'Improved revenue streams', 'I do not know']",
        "answerId": "[\"RMIStm3aFuKg\",\"hHpSnXOEBVeo\",\"1p8ZavN8Ov8j\",\"EFyErGQZaP86\",\"FgXOBm4AO0QU\",\"96ZkhFDm6DUs\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "C7XucjtCtMEQ",
        "type": "multiple",
        "questions": "How did you solve the challenge(s) you identified?",
        "promptName": "",
        "buttonText": "",
        "category": "General",
        "rows": "",
        "answers": "['Developed an internal solution', 'Outsourced the solution', 'It has not been solved yet']",
        "answerId": "[\"GsPueu2RyD11\",\"JQ5n1yAxSjnj\",\"vdoBLKWvDTB8\"]",
        "dataCapture": "",
        "autoFill": ""
    },
    {
        "questionId": "AnRWtI3LEqbF",
        "type": "single",
        "questions": "###NAME, would you be willing to take our survey again in 4 months?",
        "promptName": "",
        "buttonText": "",
        "category": "General",
        "rows": "",
        "answers": "['Yes', 'No']",
        "answerId": "[\"Hja08wTQBYEP\",\"nww9GScQL2Qd\"]",
        "dataCapture": "",
        "autoFill": ""
    }
]

module.exports = {newSurveyCSVARRAY, frozenCSVARRAY, newFrozen };